### ISSUE TITLE
Fails in WP 4.5.x

### ISSUE THREAD

**Issue by ronnyandre** [dtbaker/wordpress-mce-view-and-shortcode-editor#13]
It's hard to find any good examples of creating TinyMCE plugins with editor preview, and this is the best one yet. However, it fails with Underscore and `wp.media.template` in WordPress 4.5.x. Any chance this code can be updated?

**Comment by dtbaker** [comment]
Thanks for letting me know, I haven't had a chance to test 4.5 yet. I'll see what I can find out tomorrow.

**Comment by ronnyandre** [comment]
Thanks for swift answer. Seems like there was some issue with parsing template (from my part). It seems to work perfectly in 4.5.1!
