### ISSUE TITLE
Not working with WP 4.2

### ISSUE THREAD

**Issue by programmin1** [dtbaker/wordpress-mce-view-and-shortcode-editor#3]
Due to some major rework they're doing in WP 4.2, this plugin doesn't show any preview.

See https://core.trac.wordpress.org/ticket/31563#comment:2

**Comment by schnerd** [comment]
Looks like the new API in 4.2 simplifies things quite a bit. Couldn't find any official documentation but was able to get things working by poking around in mce-view.js of the 4.2rc source. This is what I'm using:

```js
	wp.mce.views.register( 'foo', {
		template: wp.media.template( 'editor-foo' ),
		getContent: function() {
			return this.template(this.shortcode.attrs.named);
		}
	});
```

**Comment by dtbaker** [comment]
Thanks guys!

I'm updating one of my themes and getting this working in 4.2 was possible. It's probably not backwards compatible but oh well. Here's the tweaks I made in my own code, copied across to this basic plugin.

Hopefully once this is finished I can update this plugin with a better full example from my theme. 

3f4779cf67a4a170f258d9605dc99c5ba1c71440
