### ISSUE TITLE
note: this will stop working in WordPress 4.2 ( April 2015 ). New code will be added once 4.2 RC is out.

### ISSUE THREAD

**Issue by jtsternberg** [dtbaker/wordpress-mce-view-and-shortcode-editor#6]
4.2 is out. :) any chance you'll be updating this code?

**Comment by gillesgoetsch** [comment]
@jtsternberg Look at the commit history, an update has happened.
Seems to work for me. Awesome enhancement for the WP Editor, thank you @dtbaker .

**Comment by jtsternberg** [comment]
Gotcha. I honestly didn't look or try because of the notice on the README.

**Comment by dtbaker** [comment]
Hey yep it should work! Sorry I'll jump in and fix this readme :)
